name = "keyan-m/cardano-account"
version = "0.0.0"
compiler = "v1.0.31-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "A wallet-less Cardano solution with usernames and passwords for a more convenient onboarding"

[repository]
user = "keyan-m"
project = "cardano-account"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v1"
source = "github"
