name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aiken-lang/setup-aiken@v1.0.2
        with:
          version: v1.1.2

      - run: aiken fmt --check
        working-directory: ./on-chain
      - run: aiken check
        working-directory: ./on-chain
      - run: aiken build
        working-directory: ./on-chain
